version: '3'
services: 
  martin:
    build: .
    env_file:
     - ./.env
    restart: always
    tty: true
    depends_on:
      - lavalink

  lavalink:
    image: "yukine/lavalink:latest"
    restart: always
    ports:
      - "2333"
      - "8080"